### ISSUE TITLE
Incorrect tokenization

### ISSUE THREAD

**Issue by eh0tka** [alisherfaz/codeanalyzer#19]
Examples:
public interface ChatInterface extends Remote {
    public
}
Result:
[Token{type=PUBLIC, value='public', startLine=1, startColumn=0}
, Token{type=INTERFACE, value='interface', startLine=1, startColumn=7}
, Token{type=NAME_EXPR, value='ChatInterface', startLine=1, startColumn=17}
, Token{type=EXTENDS, value='extends', startLine=1, startColumn=31}
, Token{type=NAME_EXPR, value='Remote', startLine=1, startColumn=39}
, Token{type=L_CURL, value='{', startLine=1, startColumn=46}
, Token{type=R_CURL, value='}', startLine=3, startColumn=0}
]
Error: missed PUBLIC token
====
public interface ChatInterface extends Remote {
    public sdfsd
}

Result:
[Token{type=PUBLIC, value='public', startLine=1, startColumn=0}
, Token{type=INTERFACE, value='interface', startLine=1, startColumn=7}
, Token{type=NAME_EXPR, value='ChatInterface', startLine=1, startColumn=17}
, Token{type=EXTENDS, value='extends', startLine=1, startColumn=31}
, Token{type=NAME_EXPR, value='Remote', startLine=1, startColumn=39}
, Token{type=L_CURL, value='{', startLine=1, startColumn=46}
, Token{type=PUBLIC, value='public', startLine=2, startColumn=4}
, Token{type=R_CURL, value='}', startLine=3, startColumn=0}
]

Error: Missed sdfsd as NAME_EXPR token

**Comment by dashakoryukova** [comment]
FUCK U WITH YOUR ISSUE FUCKING PM

**Comment by dashakoryukova** [comment]
У меня все работает. Господа,не забываем запуллиться прежде чем отвлекать других. Проблема была решена неделю назад.

**Comment by eh0tka** [comment]
Все ветки актуальные
Запускаю из девелопа
Оба приведенных примера по-прежнему не содержат в себе нужного значения
Давай посмотрим на твоей машине? Или на моей?

**Comment by alisherfaz** [comment]
I confirm that the issue is reproduced in develop, latest commit fcb54d4e5d663c91da7e02f82e56d156bc50a6f3

**Comment by alisherfaz** [comment]
Fix is verified
